#!/bin/bash
 
build() 
{
	add_module 'squashfs'
	add_module 'loop'
	add_module 'overlay'

	add_file "/etc/passwd"
	add_file "/etc/shadow"
	add_file "/etc/group"
	add_file "/etc/gshadow"

        add_binary "/usr/bin/sed"
        add_binary "/usr/bin/pkill"
        add_binary "/usr/bin/curl"
	add_full_dir /etc/ssl
    	add_full_dir /etc/ca-certificates

        add_runscript

}
 
help() 
{
        cat <<HELPEOF
Mount a squashed flat-file directory with OverlayFS on /, add SSL support
HELPEOF
}
