#!/bin/bash

build() {
    add_runscript

    add_binary curl

    add_full_dir /etc/ssl
    add_full_dir /etc/ca-certificates
}

help() {
cat<<HELPEOF
  This hook loads the necessary modules for boot via PXE and HTTP.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
