#!/bin/bash
 
build() 
{
	add_module 'squashfs'
	add_module 'loop'
	add_module 'overlay'

        add_binary "sed"
        add_binary "pkill"

        add_runscript

}
 
help() 
{
        cat <<HELPEOF
Mount a squashed flat-file directory with OverlayFS on /
HELPEOF
}
