#!/bin/bash

if [[ ! -f "/usr/lib/libdialog.so" ]];
then
  echo "Please run the following: sudo ln -s /usr/lib/libdialog.so.1.2 /usr/lib/libdialog.so"
  echo "This package will fail to build otherwise."
fi
