=== Starting a Desktop Environment
You can install any desktop environment or window manager you would like via <<changing_the_installed_software,package lists>>! From there, it's simply a matter of setting the correct Systemd unit to start automatically. The https://wiki.archlinux.org/index.php/[Arch wiki^] has a lot of useful information here. As an example, I'll include http://lxde.org/[LXDE^] instructions here.

Simply create a symlink for the target. In the `<basedir>/overlay/etc/systemd/system/` directory:

 ln -s /usr/lib/systemd/system/lxdm.service display-manager.service

==== Autologin (LXDE)
Many desktop environments even offer an automatic login feature directly through the desktop manager (LXDM, in LXDE's case).

Again, using LXDE as an example, create a file at `<basedir>/overlay/etc/lxdm/lxdm.conf`:

 [base]
 autologin=bdisk
 greeter=/usr/lib/lxdm/lxdm-greeter-gtk
 [server]
 arg=/usr/bin/X -background vt1
 [display]
 gtk_theme=Adwaita
 bottom_pane=1
 lang=1
 keyboard=0
 theme=Industrial
 [input]
 [userlist]
 disable=0
 white=
 black=

LXDE will then automatically log in with the user `bdisk` (note the second line, right under `[base]`) whenever started.